### ISSUE TITLE
$DRY_RUN

### ISSUE THREAD

**Issue by ole-tange** [kidd/scripting-field-guide#3]
This:

~~~
if [[-n $DRY_RUN ]]; then
  curl () {
    echo curl $@
  }
fi
~~~

should be this:

~~~
if [[ -n "$DRY_RUN" ]]; then
  curl () {
    echo curl "$@"
  }
fi
~~~

Otherwise you cannot pass two spaces as argument:

~~~
curl "two  spaces"
~~~

Also you might find https://gitlab.com/ole.tange/tangetools/-/blob/master/find-first-fail/find-first-fail interesting.

**Comment by kidd** [comment]
Thanks for the bug report. Fixed it.

Thanks for the link to the script, I'll incorporate it into my toolbox and will write about it when I find some use case of mine.

Thanks for GNU Parallel :).
